let SocialType = {
  SET_EXPLOR_POSTS:"SET_EXPLOR_POSTS",
  SET_POST:"SET_POST",
  SET_PROFILE:"SET_PROFILE",
  SET_IS_SEARCH:"SET_IS_SEARCH",
  SET_SEARCH_USERS:"SET_SEARCH_USERS"
};

export default SocialType;
